### ISSUE TITLE
undefined method `update_attribute_without_validatons_or_callbacks'

### ISSUE THREAD

**Issue by jazzdragon** [devise-security/devise-security#106]
Upgraded from 0.12.0 to 0.14.2 and started getting the error above.
Looks like it's coming from devise-security/models/session_limitable.rb:22

cheers!

**Comment by jazzdragon** [comment]
Looks like it was introduced by 9fb28aa8947591fbfeecaa3e5d4b6edd4e336c0e

**Comment by olbrich** [comment]
@jazzdragon are you setting `DEVISE_ORM` anywhere, and if so, what are you setting it to?

**Comment by 6temes** [comment]
I have the same issue after upgrading from `0.14.1` to `0.14.2`

**Comment by olbrich** [comment]
looks like if your model didn't also use `secure_validateable` or `password_archiveable` then the compatibility module that defines this method would not get loaded.

@jazzdragon @6temes try using the branch from #107 and see if it fixes your problem.

**Comment by 6temes** [comment]
I can confirm that the branch from #107 fixes the issue.

Just for the record, the code that was triggering the issue in my project was that method in `ApplicationController`:

![image](https://user-images.githubusercontent.com/5655861/58364143-7c0a2f00-7eea-11e9-8a69-00631aa91136.png)
