### ISSUE TITLE
undefined method `devise_modules' for #<Lead:0x000000000c9ccfc8>

### ISSUE THREAD

**Issue by JHirte** [devise-security/devise-security#370]
After updating devise-security from 0.14.3 to 0.16.0 we encountered failing tests in our application. I'm not sure what's happening here. The error occurs deep inside the Rails-Stack. Some debugging led me to this commit: https://github.com/devise-security/devise-security/commit/37b720179fc64a25ef308baa9e3badc6bf6e5400

**Comment by dillonwelch** [comment]
That method comes from the base `devise` gem - https://github.com/heartcombo/devise/blob/8593801130f2df94a50863b5db535c272b00efe1/lib/devise/models/authenticatable.rb#L69

What devise moduels are you using in your `Lead` model?

**Comment by JHirte** [comment]
Lead doesn't use devise at all. From two other models we get:

:database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable, :lockable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]

and

:database_authenticatable, :recoverable, :trackable, :validatable, :lockable, :password_expirable, :password_archivable, session_limitable, :admin_timeoutable

admin_timeoutable is some own cruft I don't know why it exists. This is not my code, I have to take care of this now.

**Comment by JHirte** [comment]
Without :session_limitable, the test case works again

**Comment by dillonwelch** [comment]
In the immediate term, can you try defining a method like this on your `Lead` model?

```ruby
def devise_modules
  []
end
```

I think our code should be updated to handle this scenario more gracefully though.

**Comment by JHirte** [comment]
Thanks, this works here
